package app

const (
	ENVVAR_LOG_LEVEL                      string = "PUBSUB_EMULATOR_LOG_LEVEL"
	ENVVAR_ENV                            string = "PUBSUB_EMULATOR_ENV"
	ENVVAR_GOOGLE_APPLICATION_CREDENTIALS string = "GOOGLE_APPLICATION_CREDENTIALS"
	ENVVAR_GOOGLE_LOCATION                string = "PUBSUB_EMULATOR_GOOGLE_LOCATION"
	ENVVAR_GOOGLE_EMBEDDING_TASK_TOPIC    string = "PUBSUB_EMULATOR_GOOGLE_EMBEDDING_TASK_TOPIC"
	ENVVAR_EMULATOR_HOST                  string = "PUBSUB_EMULATOR_HOST"
	ENVVAR_GOOGLE_PROJECT_ID              string = "PUBSUB_EMULATOR_GOOGLE_PROJECT_ID"
	ENVVAR_TOPIC_ID                       string = "PUBSUB_EMULATOR_TOPIC_ID"
	ENVVAR_SUBSCRIPTION_ID                string = "PUBSUB_EMULATOR_SUBSCRIPTION_ID"
	ENVVAR_DLT_TOPIC_ID                   string = "PUBSUB_EMULATOR_DLT_TOPIC_ID"
)
